name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test_msg_type_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: feishu notify
        uses: xiachufang/actions-feishu@v1.2
        with:
          webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          title: I'm title
          content: |
            I'm message body

            from: ${{ github.repository }}
  test_msg_type___template__:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        id: set-template-values
        with:
          script: |
            return JSON.stringify({
              title: "æ¯æ—¥ä¸€é—®",
              text: "åƒäº†å—?ğŸš",
              yes_button_text: "åƒäº†",
              no_button_text: "æ²¡åƒ",
            })
          result-encoding: string
      - uses: ./
        with:
          webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          message_type: "__template__"
          msg_template_path: '.github/feishu_msg_tmpl/example.json'
          msg_template_values: "${{steps.set-template-values.outputs.result}}"