name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test_msg_type_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          title: I'm title
          content: |
            I'm message body

            from: ${{ github.repository }}
  test_msg_type_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        id: set-template-values
        with:
          script: |
            return JSON.stringify({
              title: "æ¯æ—¥ä¸€é—®",
              text: "åƒäº†å—?ğŸš",
              yes_button_text: "åƒäº†",
              no_button_text: "æ²¡åƒ",
            })
          result-encoding: string
      - uses: ./
        with:
          webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          message_type: "template"
          msg_template_path: '.github/feishu_msg_tmpl/example.json'
          msg_template_values: "${{steps.set-template-values.outputs.result}}"
  test_msg_type_template_by_using_bin_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        id: set-template-values
        with:
          script: |
            return JSON.stringify({
              title: "æ¯æ—¥ä¸€é—®(2)",
              text: "åƒäº†å—?ğŸš",
              yes_button_text: "åƒäº†",
              no_button_text: "æ²¡åƒ",
            })
          result-encoding: string
      - name: Send feishu message
        env:
          ACTIONS_FEISHU_TAG_ID: '1.3.1'
          INPUT_WEBHOOK: "${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}"
          INPUT_MESSAGE_TYPE: template
          INPUT_MSG_TEMPLATE_PATH: ".github/feishu_msg_tmpl/example.json"
          INPUT_MSG_TEMPLATE_VALUES: "${{ steps.set-template-values.outputs.result }}"
        run: |
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/$ACTIONS_FEISHU_TAG_ID/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu
