name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test_msg_type_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          title: I'm title
          content: |
            I'm message body

            from: ${{ github.repository }}
  test_msg_type_post_by_using_bin_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send feishu message
        env:
          ACTIONS_FEISHU_TAG: 'v1.3.1'
          INPUT_WEBHOOK: "${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}"
          INPUT_TITLE: "I'm title"
          INPUT_CONTENT: "I'm message body\nfrom: ${{ github.repository }}"
        run: |
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu
  test_msg_type_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        id: set-template-values
        with:
          script: |
            return JSON.stringify({
              title: "ÊØèÊó•‰∏ÄÈóÆ",
              text: "ÂêÉ‰∫ÜÂêó?üçö",
              yes_button_text: "ÂêÉ‰∫Ü",
              no_button_text: "Ê≤°ÂêÉ",
            })
          result-encoding: string
      - uses: ./
        with:
          webhook: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          message_type: "template"
          msg_template_path: '.github/feishu_msg_tmpl/example.json'
          msg_template_values: "${{steps.set-template-values.outputs.result}}"
  test_msg_type_template_by_using_bin_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        id: set-template-values
        with:
          script: |
            return JSON.stringify({
              title: "ÊØèÊó•‰∏ÄÈóÆ(2)",
              text: "ÂêÉ‰∫ÜÂêó?üçö",
              yes_button_text: "ÂêÉ‰∫Ü",
              no_button_text: "Ê≤°ÂêÉ",
            })
          result-encoding: string
      - name: Send feishu message
        env:
          ACTIONS_FEISHU_TAG: 'v1.3.1'
          INPUT_WEBHOOK: "${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}"
          INPUT_MESSAGE_TYPE: template
          INPUT_MSG_TEMPLATE_PATH: ".github/feishu_msg_tmpl/example.json"
          INPUT_MSG_TEMPLATE_VALUES: "${{ steps.set-template-values.outputs.result }}"
        run: |
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu
